controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hoverboard_base_controller:
      type: diff_drive_controller/DiffDriveController

hoverboard_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.45
    wheel_radius: 0.0825

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 4.5
        min_velocity: -4.5
        max_acceleration: 0.2
        max_jerk: 0.0
        min_jerk: 0.0

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 4.5
        min_velocity: -4.5
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0
